name: End-to-end CAD flow CI smoketest

on:
  push:
    branches:
      - main
      - test-ci
  pull_request:

jobs:
  test:
    runs-on: [self-hosted] # TODO: replace with something centrally admined

    steps:
      # Step 1: Create a temporary directory
      - name: Create temporary directory
        run: |
          TMP_DIR=$(mktemp -d)
          echo "Temporary directory created at: $TMP_DIR"
          echo "TMP_DIR=$TMP_DIR" >> $GITHUB_ENV

        # Clone this repo
      - name: Checkout
        uses: actions/checkout@v4.1.6


      # Step 3: Check out the specific commit
      - name: Check out the commit being tested
        run: |
          cd $TMP_DIR/repo
          git fetch --depth=1 origin ${{ github.sha }}
          git checkout ${{ github.sha }}

      # Step 4: Navigate to the `vlsi` directory and run `make`
      - name: Run `make` in the `vlsi` directory
        run: |
          cd $TMP_DIR/repo/e2e
          make build

      # Step 5: Clean up the temporary directory
      - name: Clean up temporary directory
        if: always() # Ensures this step always runs
        run: |
          echo "Cleaning up temporary directory: $TMP_DIR"
          rm -rf $TMP_DIR
